Updated the installation guide
SJSU-CS-systems-group/piman pull request #8
Opened 2020-11-03 17:20 UTC by mcinerneym

Modified the Installation Guide to be more accurate and updated the pictures

2020-11-03 17:58 UTC, evanho9 commented
Looks good! Tested by team Machester

2020-11-03 18:07 UTC, nguyenvic commented
Looks good!

2020-11-04 08:53 UTC, evanho9 approved these changes

2020-11-04 11:51 UTC, nguyenvic approved these changes

2020-11-05 00:46 UTC, breed requested changes
fix the paths and you should be good to go.

2020-11-05 00:46 UTC, breed commented on Installation_Guide.md
> +			WorkingDirectory=/home/usr/piman/monitoring
need to discuss this to agree on the path between PRs

2020-11-05 00:46 UTC, breed commented on Installation_Guide.md
> +			ExecStart=sh /home/usr/piman/monitoring/monitoring_piman.sh
you shouldn't need the "sh "

2020-11-07 06:15 UTC, breed requested changes

2020-11-07 06:15 UTC, breed commented on Installation_Guide.md
> +			WorkingDirectory=/home/usr/local/share/piman/monitoring
these paths are not correct.

2020-11-07 19:12 UTC, breed approved these changes
thank you

2020-11-07 19:12 UTC, merged